services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /mnt/Ale/HomeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard
    ports:
      - "51820:51820/udp"  # WireGuard VPN port
      - "51821:51821/tcp"  # Web UI access
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - WG_HOST=auto # Automatically detects and uses the server's public IP
      - WG_PORT=51820
      - WG_PEER_LIMIT=10  # Sets the limit for the number of peers
      - WG_DEFAULT_ADDRESS=10.13.13.1/24  # Adjust the subnet to match your internal preferences
      - WG_ALLOWED_IPS=0.0.0.0/0
      - PASSWORD=your_web_ui_password  # Set a strong password for Web UI access
    volumes:
      - ./config/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.6

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Pacific/Auckland'
      WEBPASSWORD: 'set_a_strong_password_here'  # Set a strong password
    volumes:
      - '/mnt/Ale/PiHole/etc-pihole:/etc/pihole/'
      - '/mnt/Ale/PiHole/dnsmasq.d:/etc/dnsmasq.d/'
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.7

networks:
  containers:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
