services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Pacific/Auckland
      - SUBDOMAINS=
      - TOKEN=
      #- LOG_FILE=true #optional
    volumes:
      - /home/pi/docker/data/duckdns/config:/config #optional
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /mnt/Ale/HomeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host


  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - WG_HOST=auto  # Ensure this is set to your actual server URL or auto-detected IP
      - WG_PORT=51820
      - WG_PEER_LIMIT=10  # Sets the limit for the number of peers
      - WG_DEFAULT_ADDRESS=10.13.13.x/24  # Adjust the subnet to match your internal preferences
      - WG_ALLOWED_IPS=0.0.0.0/0
      - PASSWORD=your_password_here  # Set a strong password for the Web UI access
    volumes:
      - ./config/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - "51820:51820/udp"  # WireGuard VPN port
      - "51821:51821/tcp"  # Web UI access
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.20.0.7  # Pi-hole as primary DNS resolver
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.6

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Pacific/Auckland'
      WEBPASSWORD: ''
    volumes:
      - '/mnt/Ale/PiHole/etc-pihole:/etc/pihole/'
      - '/mnt/Ale/PiHole/dnsmasq.d:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
#    cap_add:
#      - NET_ADMIN
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.7


networks:
  containers:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
