version: '3.7'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /mnt/Ale/HomeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - SERVERURL=auto #optional | Ip or domain of your server
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0/24 # Ensure correct CIDR format
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.20.0.7
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.6

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Pacific/Auckland'
      WEBPASSWORD: 'set_a_strong_password_here'  # Set a strong password
    volumes:
      - '/mnt/Ale/PiHole/etc-pihole:/etc/pihole/'
      - '/mnt/Ale/PiHole/dnsmasq.d:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
#    cap_add:
#      - NET_ADMIN
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.7

networks:
  containers:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
